### PR TITLE
[CI] Disable Travis.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Review by nim65s — APPROVED** [review]

**Comment by jmirabel** [comment]
@nim65s this can be done in many other sot projects, can't it ?

**Comment by nim65s** [comment]
yes, especially where it doesn't work.

**Comment by nim65s** [comment]
I just activated https://github.com/apps/gepetto-dashboard on the whole Stack-of-Tasks project. Gitlab-CI will now run and report for every push and every PR. It will also warn for PRs on master instead of devel, and synchronise projects from github to gitlab.

**Comment by olivier-stasse** [comment]
@nim65s I just removed the webhook on travis for this repo.
Thanks a lot for the github app. Looking forward in seeing how it works.

**Pull request merged**
