### PR TITLE
[Python] Add convenient function to create a robot from a URDF file.

### PR DESCRIPTION
**Pull request by jmirabel**
This also adds the possibility to remove joints from Python. This avoids the need to create a specific URDF file for SoT.

### CODE REVIEW

**Comment by olivier-stasse** [comment]
Thank you very much for this valuable contribution.
Could you update your PR to fix the conflicts ?

Do you think that there is a simple way to have unit tests ?

**Comment by jmirabel** [comment]
I put this in my todo list.

**Comment by jmirabel** [comment]
I see Python unit tests in this package but CMake does not add them to target test. How are we suppose to use them ?

**Comment by olivier-stasse** [comment]
@jmirabel commit 92f75f2d8e642 allows python tests.
Unfortunately the one currently in the package needs the robotViewer and are assuming a specific robot. They are likely to be removed soon.
You can use the examples in sot-core/tests/python or sot-talos-balance/tests/python which are following the same structure than provided here.

**Comment by jmirabel** [comment]
This is ready now.

**Pull request merged**
