### PR TITLE
[dynamic-pinocchio] Fix pb on computing AngularMomentum.

### PR DESCRIPTION
**Pull request by olivier-stasse**
Fix#44

### CODE REVIEW

**Comment by gabrielebndn** [comment]
Hi, could you make a release integrating these changes?

**Comment by nim65s** [comment]
I will.

**Comment by nim65s** [comment]
@gabrielebndn : you can now use `robotpkg-py27-sot-dynamic-pinocchio-v3` v3.3.0r1 in the 16.04 robotpkg-wip binary repository.

**Comment by gabrielebndn** [comment]
@nim65s Cool, thanks a lot!

**Comment by gabrielebndn** [comment]
@nim65s: I installed `robotpkg-py27-sot-dynamic-pinocchio-v3`. However, I see there is also `robotpkg-sot-dynamic-pinocchio-v3` which was already installed and was *not* upgraded. Is it normal? Should I run `sudo apt-get install robotpkg-sot-dynamic-pinocchio-v3` too? Shouldn't it be automatic?

**Comment by gabrielebndn** [comment]
Actually, it seems it was automatically upgraded this morning to `3.3.0`, but not to `3.3.0r1`. Anyhow, the change I was interested in seems to be effective

**Pull request merged**
