### PR TITLE
[python] Add method to get actuated joints

### PR DESCRIPTION
**Pull request by florent-lamiraux**
in python class AbstractRobot.

### CODE REVIEW

**Comment by nim65s** [comment]
It would be nice to add a unit test for this :)

**Comment by florent-lamiraux** [comment]
I have been trying for the past two hours to add a test, but it is too painful. Handling the state dimension is very difficult since the dimension is different from pinocchio configuration vector and the asumption that the robot has a freeflyer joint is made at many places.

**Comment by olivier-stasse** [comment]
Is it not possible to add a test in `./tests/python/humanoid_robot.py` ?

**Comment by florent-lamiraux** [comment]
> Is it not possible to add a test in `./tests/python/humanoid_robot.py` ?

That is exactly what I tried. To make the new command work, I need to call `AbstractHumanoidRobot.initializeRobot`. For that, I need to implement method `defineHalfsitting` in the test. The way things are implemented today makes it difficult to  predict the size of this configuration for any type of robot. I think we need to agree on a consistent way of defining the `state` and `control` vectors.

**Pull request merged**
